apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: techtalk-demo-group
subjects:
  - kind: Group
    # Name field should match the group configured in the
    # `allow.kubernetes_groups` of a role belonging to the user you wish to
    # grant access to.
    name: techtalk-demo
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  # "view" is a default ClusterRole that grants read-only access to resources
  # See: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles
  name: view
  apiGroup: rbac.authorization.k8s.io
