replicaCount: 3
ui:
  message: "WeShape Tech Talks Feb 2023"
redis:
  enabled: true
ingress:
  enabled: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: ${issuer}
  hosts:
    - host: ${ingress_fqdn}
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
   - secretName: podinfo-tls
     hosts:
       - ${ingress_fqdn}
