apiVersion: resources.teleport.dev/v5
kind: TeleportRole
metadata:
  name: ${teleport_role}
  namespace: ${namespace}
spec:
  allow:
    app_labels:
      aws_account_id: "${account}"
    aws_role_arns:
      - arn:aws:iam::${account}:role/${iam_role_name}
    db_labels:
      Environment: none
    kubernetes_labels:
      Environment: none
