apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: podinfo-tls
  namespace: default
spec:
  dnsNames:
    - podinfo.devops-consultants.net
  issuerRef:
    name: letsencrypt-prod-dns
    kind: ClusterIssuer
  secretName: podinfo-tls
  usages:
    - digital signature
    - key encipherment
