name: Demo Secure Remote Access using Teleport

on:
  workflow_dispatch:

jobs:
  ssh_access:
    permissions:
      id-token: write
      contents: read
    name: SSH-Access
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch Teleport binaries
        uses: teleport-actions/setup@v1
        with:
          version: 12.0.2

      - name: Fetch credentials using Machine ID
        id: auth
        uses: teleport-actions/auth@v1
        with:
          proxy: teleport.devops-consultant.guru:443
          token: github-token
          certificate-ttl: 1h

      - name: List nodes
        run: tsh -i ${{ steps.auth.outputs.identity-file }} ls

      - name: Check uptime
        run: tsh -i ${{ steps.auth.outputs.identity-file }} ssh root@qnapvm.home uptime

      - name: Check memory
        run: tsh -i ${{ steps.auth.outputs.identity-file }} ssh root@qnapvm.home vmstat

      - name: Check cpu
        run: tsh -i ${{ steps.auth.outputs.identity-file }} ssh root@qnapvm.home cat /proc/cpuinfo

  k8s_access:
    permissions:
      id-token: write
      contents: read
    name: K8S-Access
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch kubectl
        uses: azure/setup-kubectl@v3

      - name: Fetch Teleport binaries
        uses: teleport-actions/setup@v1
        with:
          version: 12.0.2

      - name: Fetch credentials using Machine ID
        uses: teleport-actions/auth-k8s@v1
        with:
          proxy: teleport.devops-consultant.guru:443
          token: github-token
          kubernetes-cluster: tech-talks

      - name: List pods
        run: kubectl get pods -A
